# Generated by Django 6.0.7 on 2026-07-24 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=50, unique=True)),
                ('obtained_at', models.DateTimeField(auto_now_add=True)),
                ('url_pdf', models.FileField(blank=True, help_text='Generated PDF certificate file.', null=True, upload_to='certificates/%Y/%m/')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='catalog.training')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'db_table': 'certificat',
                'constraints': [models.UniqueConstraint(fields=('user', 'training'), name='uniq_user_training_certificate')],
            },
        ),
        migrations.CreateModel(
            name='ChapterProgress',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progresses', to='catalog.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chapter progress',
                'verbose_name_plural': 'Chapter progresses',
                'db_table': 'progression_chapitre',
                'constraints': [models.UniqueConstraint(fields=('user', 'chapter'), name='uniq_user_chapter_progress')],
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('completed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=20)),
                ('last_consulted_at', models.DateTimeField(auto_now=True)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='catalog.training')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progress',
                'verbose_name_plural': 'Progress records',
                'db_table': 'progression',
                'constraints': [models.UniqueConstraint(fields=('user', 'training'), name='uniq_user_training_progress')],
            },
        ),
    ]
